### ISSUE TITLE
Wrong `n_control` imputation in `cohen` function

### ISSUE THREAD

**Issue by Feat-FeAR** [MrHedmad/fast-cohen#3]
https://github.com/MrHedmad/fast-cohen/blob/912ceccfaf034c40385d87f2ea3f13c32822e7ae/src/main.rs#L171

should be instead

```rust
let n_control: T = NumCast::from(control.len()).unwrap();
```
Notably, your `test_cohen()` passed because in that case `n_case == n_control`....
I suggest implementing a new test with 2 vectors of different lengths.

Time for a `fast-cohen 0.1.1` :-D ?

**Comment by MrHedmad** [comment]
Fuck me!

**Comment by MrHedmad** [comment]
Fixed and added asymmetric tests to check for it in the future.
