### ISSUE TITLE
Bad (misleading) variable name for the "pooled standard deviation"

### ISSUE THREAD

**Issue by Feat-FeAR** [MrHedmad/fast-cohen#5]
In the following lines, `pooled_var` should be replaced with `pooled_std` (or something similar), to avoid confusion when reading/debugging the code.

https://github.com/MrHedmad/fast-cohen/blob/912ceccfaf034c40385d87f2ea3f13c32822e7ae/src/main.rs#L173-L182

**Comment by MrHedmad** [comment]
This was fixed in 3fc4338
